name: deploy to Internet Computer

on:
  workflow_dispatch:
jobs:
  test-deploy:
    runs-on: ubuntu-latest
    name: A job to deploy canisters to the IC
    steps:
      - uses: actions/checkout@v2
      - name: get deps
        run: cargo install ic-cdk-optimizer --target root 
      - name: Deploy canisters
        id: deploy
        uses: webi-ai/IC-Deploy-Action-rust@main
        with:
          identity: ${{ secrets.DFX_IDENTITY }}
          dfx_params: --no-wallet

      - name: Show success message
        run: echo success!
